[package]
name = "fpp_lexer"

version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
memchr = "2.7.4"
unicode-ident = "1.0.22"

[dev-dependencies]
pretty_assertions = "1.4.1"
