[package]
name = "fpp_lsp_parser"

version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
fpp_lexer = { path = "../fpp_lexer" }
pretty_assertions = "1.4.1"

rowan = "0.16.1"
drop_bomb = "0.1.5"
